# Generated by Django 3.0 on 2020-01-25 19:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('index', '0004_user_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='image',
            field=models.ImageField(blank=True, default='articles/default.jpg', upload_to='articles/'),
        ),
        migrations.AlterField(
            model_name='user',
            name='image',
            field=models.ImageField(blank=True, default='doctors/default.jpg', upload_to='doctors/'),
        ),
    ]
